### ISSUE TITLE
Does not work with repos which do not have `master` as default branch

### ISSUE THREAD

**Issue by livingston** [codejamninja/dotstow#14]
If we use a repo with default branch as `main` it fails with the following error,

> no reference found for shorthand 'master'

The `dotstow pull` command defaults to `master` branch.

Though, 
https://github.com/codejamninja/dotstow/blob/9fa430b47c02c6962cec22be3ead6aa4fdffc63a/src/services/git.ts#L34 allows us to pass in a different **branch**,

the command `pull`,
https://github.com/codejamninja/dotstow/blob/9fa430b47c02c6962cec22be3ead6aa4fdffc63a/src/commands/pull.ts#L14-L19 does not accept any flags other than `debug`

Can you please update `pull` command to accept `branch` as a parameter?

**Comment by clayrisser** [comment]
Ok thanks @livingston. Could you send a PR?
