### ISSUE TITLE
error authenticating: no auth sock variable

### ISSUE THREAD

**Issue by clayrisser** [codejamninja/dotstow#5]
I get the following error in the Windows subshell for linux

```
$ dotstow sync
error authenticating: no auth sock variable
```

**Comment by toddpi314** [comment]
Seeing this on Debian too, when fetching against an `git@` over ssh

**Comment by toddpi314** [comment]
github is recommending `ed25519` for SSH keygen these days. (ref: https://docs.github.com/en/github-ae@latest/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)

This means we can't explicitly rely on the id_rsa* to be available in ~/.ssh anymore: https://github.com/codejamninja/dotstow/blob/master/src/services/git.ts#L13-L14

**Comment by toddpi314** [comment]
Looks like this was cleared up by forcing usage of the ssh-agent for nodegit.
```
ssh-agent bash
```

**Comment by clayrisser** [comment]
Yeah, I think that happens when the ssh agent isn't running. I've had it happen in systems like arch linux that don't automatically turn ssh agent on.

**Comment by clayrisser** [comment]
Shouldn't be an issue anymore now that it's rewritten in bash.
